### ISSUE TITLE
Incorrect VertexCover implementation

### ISSUE THREAD

**Issue by VaeterchenFrost** [hmarkus/dp_on_dbs#3]
The current VC impl does not solve vertex cover.
Probably the issue is with https://github.com/hmarkus/dp_on_dbs/blob/5d929929cf5730893f7667be2f1ca72234847fe1/dpdb/problems/vertexcover.py#L51

See the correct impl in https://github.com/hmarkus/dp_on_dbs/blob/5d929929cf5730893f7667be2f1ca72234847fe1/paper/PADL2020/dpdb-padl2020.pdf
on problem MinVC

Current (incorrect) SQL Queries for 

`p edge 9 16
e 1 2
e 1 3
e 2 3
e 1 4
e 3 4
e 1 5
e 4 5
e 1 6
e 5 6
e 1 7
e 6 7
e 1 8
e 7 8
e 1 9
e 2 9
e 8 9`

are: 

> 6: {1, 3, 4, 5}
> WHERE (v3 OR v4 OR v5 OR v1) AND (v1 OR v4 OR v3) AND (v1 OR v3 OR v5 OR v4) AND (v1 OR v4 OR v5)
> 5: {1, 2, 3, 5}
> WHERE (v1 OR v3 OR v2)
> 4: {1, 2, 5, 9}
> WHERE (v1 OR v2 OR v9)
> 3: {1, 5, 6, 9}
> WHERE (v1 OR v5 OR v6)
> 2: {1, 6, 7, 9}
> WHERE (v1 OR v6 OR v7)
> 1: {1, 7, 8, 9}
> WHERE (v1 OR v7 OR v9 OR v8)

so obviously 1 node v1 is a solution to the problem instead of 4 nodes.

Correct local problem filter:
            ([[u1]] OR [[v1]]) AND ... ([[uN]] OR [[vN]])
            See treedecomp.node for details.

**Comment by VaeterchenFrost** [comment]
Fixed filter naively, but there seems to be an additional problem. Likely in
https://github.com/hmarkus/dp_on_dbs/blob/5d929929cf5730893f7667be2f1ca72234847fe1/dpdb/problems/vertexcover.py#L21

**Comment by VaeterchenFrost** [comment]
All testcases work with the naive 
```python
check = []
        for pos,c in enumerate(node.vertices[:-1]):
            # if node.needs_introduce(c):
                # print(self.edges[c])
                nv = [(v, c) for v in self.edges[c] if
                      v in node.vertices[pos+1:]] # don't connect backwards
                for edge in nv:
                    check.append(" OR ".join(map(var2col, edge)))
                    # print('check', check)
        if check:
            print("WHERE ({})".format(") AND (".join(check)))
            return "WHERE ({})".format(") AND (".join(check))
        else:
            return ""
```

but not the one instance with 100 nodes, 552 edges
dpdb: #bags: 61 tree_width: 15  #vertices: 100 #leafs: 10 #edges: 60
where it does always report vc size 90 instead of 82
Two other instances with 100 nodes and more/less edges work correctly...
Still investigating

**Comment by hmarkus** [comment]
Thx, fixed.
