### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'minor_graph'

### ISSUE THREAD

**Issue by vuphan314** [hmarkus/dp_on_dbs#8]
Hi @hmarkus @daajoe,

I got an error with nestHDB on a simple SAT instance:
```
$ cat f.cnf 
p cnf 2 1
1 2 0
```

The error:
```
$ ./dpdb.py -f f.cnf sat
[INFO] dpdb: Using tree decomposition seed: 0
[INFO] dpdb: Parsing input file
[INFO] dpdb: Running htd
[INFO] dpdb: Parsing tree decomposition
Traceback (most recent call last):
  File "./dpdb.py", line 177, in <module>
    solve_problem(cfg,**vars(args))
  File "./dpdb.py", line 94, in solve_problem
    td = TreeDecomp(tdr.num_bags, tdr.tree_width, tdr.num_orig_vertices, problem.get_root(tdr.bags, tdr.adjacency_list, tdr.root), tdr.bags, tdr.adjacency_list)
TypeError: __init__() missing 1 required positional argument: 'minor_graph'
```

The offending line:
https://github.com/hmarkus/dp_on_dbs/blob/9ca5d61b3abe058bc9e2858ca41d0dd273c0479d/dpdb.py#L94

The class constructor:
https://github.com/hmarkus/dp_on_dbs/blob/9ca5d61b3abe058bc9e2858ca41d0dd273c0479d/dpdb/treedecomp.py#L1-L6

Branch: [`nesthdb`](https://github.com/hmarkus/dp_on_dbs/tree/9ca5d61b3abe058bc9e2858ca41d0dd273c0479d)

Thanks.

**Comment by vuphan314** [comment]
I am unsure whether the [`nesthdb` branch in this repository](https://github.com/hmarkus/dp_on_dbs/tree/nesthdb) or the [Dropbox version](https://tinyurl.com/nesthdb) is more recent for nestHDB.

I made a clone of the Dropbox version and created a different issue there:
https://github.com/vuphan314/nesthdb/issues/1

**Comment by hmarkus** [comment]
the nesthdb branch is the current version. please use nesthdb.py instead of dpdb.py

**Comment by vuphan314** [comment]
Thanks. I created pull request #9 to make `nesthdb` easier to run.
